name: Bug Report
description: Report a problem with TinyUSB Library
labels: 'Bug'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        It's okay to leave some blank if it doesn't apply to your problem.

  - type: dropdown
    attributes:
      label: Operating System
      options:
              - Linux
              - MacOS
              - RaspberryPi OS
              - Windows 7
              - Windows 10
              - Windows 11
              - Others
    validations:
      required: true

  - type: input
    attributes:
      label: IDE version
      placeholder: e.g Arduino 1.8.15
    validations:
      required: true

  - type: input
    attributes:
      label: Board
      placeholder: e.g Feather nRF52840 Express
    validations:
      required: true
      
  - type: input
    attributes:
      label: BSP version
      description: "Release version or github latest"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Sketch
      placeholder: |
        e.g Bluefruit52Lib/examples/Peripheral/bleuart
        If it is custom sketch, please provide links to your minimal sources or as attached files.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened ?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce ?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error      
    validations:
      required: true

  - type: textarea
    attributes:
      label: Debug Log
      placeholder: Serial output when IDE's Debug Mode Level to 1 or 2 as attached txt file.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
