blank_issues_enabled: false
contact_links:
  - name: Adafruit Support Forum
    url: https://forums.adafruit.com
    about: If you have other questions or need help, post it here.
  - name: Discussion
    url: https://github.com/adafruit/Adafruit_nRF52_Arduino/discussions
    about: If you have other questions or need help, post it here.
