name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
    - name: Checkout Adafruit_nRF52_Arduino  
      uses: actions/checkout@v1
      with:
        submodules: true      
    - name: Checkout travis-ci-arduino
      uses: actions/checkout@v2
      with:
         repository: adafruit/travis-ci-arduino
         path: ci
